---
title: "BD_inclass1"
author: "JiminLee_2229027"
date: "2023-09-08"
output: word_document
---
```{r}
setwd('/Users/jimin/Desktop/지민/ewha/2023-2/BD' )
```

[1] "E" "F" "E" "F" "E" "F" "E" "F" "E" "F"
```{r}
rep(c('E','F'), 5)
```


```{r}
# letters는 소문자 a-z를 저장하고 있다. 
rep(letters[1:5],1:5)
```
3)
[1] 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33
[18] 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
[35] 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99 
```{r}
seq(from=1,to=100,by=2)
2*(1:50)-1
```

```{r}
install.packages("UsingR", dependencies=TRUE, repos = "http://cran.us.r-project.org")
```

```{r}
library('UsingR')
data(primes)
```
1) primes에는 몇 개의 소수가 있는가?
```{r}
length(primes)
```
2) 1부터 100까지는 몇 개의 소수가 있는가?
```{r}
# 1)
sum(primes<=100)

# 2)
p.100 <- primes[primes<=100]
length(p.100)
```

3) 1부터 1000까지의 소수들의 평균은 얼마인가?
```{r}
p.1000 <- primes[primes<=1000]
mean(p.1000)
```

4) 1부터 1000까지의 소수들의 표준편차는 얼마인가?
```{r}
sd(p.1000)
```

5) 1000부터 2003 사이의 소수만을 포함하는 벡터 prime2를 만드시오
```{r}
prime2 <- primes[primes>=1000 & primes<=2003]
prime2
```
3. 다음의 데이터를 이용하여 1)~6)까지의 명령을 수행하시오.
-2 5 13 -9 -15 7 18 -34 15 -16
1) 데이터 벡터 Y를 만드시오.
```{r}
Y <- c(-2,5,13,-9,-15,7,18,-34,15,-16)
Y
```
2) 각 데이터의 절대값으로 구성된 벡터 Y2를 만드시오.
```{r}
abs(Y)
```

3) 각 데이터의 제곱의 합을 구하시오.
```{r}
sum(Y**2)
```

4) 각 데이터에서 10를 뺀 값들을 구하시오.
```{r}
Y-10
```

5) 벡터 Y2의 최소값과 최댓값을 구하시오.
```{r}
min(Y)
max(Y)
range(Y) # min, max를 동시에 
```

6) 벡터 Y에서 0보다 큰 값들만으로 구성된 벡터 YLARGE를 만들고 결과를 보이시오.
```{r}
YLARGE <- Y[Y>0]
YLARGE
```
